export const PermissionsPermissionNodes = {
  UPDATE_PERMISSIONS: "PERMISSIONS.UPDATE_PERMISSIONS",
  CREATE_PERMISSIONS: "PERMISSIONS.CREATE_PERMISSIONS",
  DELETE_PERMISSIONS: "PERMISSIONS.DELETE_PERMISSIONS",
  GET_PERMISSIONS: "PERMISSIONS.GET_PERMISSIONS",
};
