export const ClockifyPermissionNodes = {
  CREATE_CLIENT: "CLOCKIFY.CREATE_CLIENT",
  UPDATE_CLIENT: "CLOCKIFY.UPDATE_CLIENT",
  DELETE_CLIENT: "CLOCKIFY.DELETE_CLIENT",
  CREATE_PROJECT: "CLOCKIFY.CREATE_PROJECT",
  UPDATE_PROJECT: "CLOCKIFY.UPDATE_PROJECT",
  DELETE_PROJECT: "CLOCKIFY.DELETE_PROJECT",
  START_TIMER: "CLOCKIFY.START_TIMER",
  STOP_TIMER: "CLOCKIFY.STOP_TIMER",
};
