export const PostCategoryPermissionNodes = {
  CATEGORY_CREATE: "POST_CATEGORY.CREATE_CATEGORY",
  CATEGORY_DELETE: "POST_CATEGORY.DELETE_CATEGORY",
  CATEGORY_UPDATE: "POST_CATEGORY.UPDATE_CATEGORY",
};
